<?php

return[
    '/'            =>'Page',
    '/home'        =>'Page',
    '/user/create' =>'user@create',
    '/bootstrap/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' =>'bootstrap',
    '/bootstrap/plugins/dropzone/min/dropzone.min.css' =>'bootstrap',
    '/bootstrap/plugins/dropzone/min/dropzone.min.js' =>'bootstrap',
    '/bootstrap/plugins/fontawesome-free/css/all.min.css' =>'bootstrap',
    '/bootstrap/plugins/icheck-bootstrap/icheck-bootstrap.min.css' =>'bootstrap',
    '/bootstrap/plugins/jqvmap/jqvmap.min.css' =>'bootstrap',
    '/bootstrap/dist/css/adminlte.min.css' =>'bootstrap',
    '/bootstrap/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' =>'bootstrap',
    '/bootstrap/plugins/daterangepicker/daterangepicker.css' =>'bootstrap',
    '/bootstrap/plugins/summernote/summernote-bs4.min.css' =>'bootstrap',
    '/bootstrap/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' =>'bootstrap',
    '/bootstrap/plugins/toastr/toastr.min.css' =>'bootstrap',
    '/bootstrap/plugins/jquery-ui/jquery-ui.min.js' =>'bootstrap',
    '/bootstrap/plugins/sweetalert2/sweetalert2.min.js' =>'bootstrap',
    '/bootstrap/plugins/bootstrap/js/bootstrap.bundle.min.js' =>'bootstrap',
    '/bootstrap/plugins/chart.js/Chart.min.js' =>'bootstrap',
    '/bootstrap/plugins/sparklines/sparkline.js' =>'bootstrap',
    '/bootstrap/plugins/jqvmap/jquery.vmap.min.js' =>'bootstrap',
    '/bootstrap/plugins/jqvmap/maps/jquery.vmap.usa.js' =>'bootstrap',
    '/bootstrap/plugins/jquery-knob/jquery.knob.min.js' =>'bootstrap',
    '/bootstrap/plugins/moment/moment.min.js' =>'bootstrap',
    '/bootstrap/plugins/daterangepicker/daterangepicker.js' =>'bootstrap',
    '/bootstrap/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' =>'bootstrap',
    '/bootstrap/plugins/summernote/summernote-bs4.min.js' =>'bootstrap',
    '/bootstrap/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' =>'bootstrap',
    '/bootstrap/dist/js/adminlte.js' =>'bootstrap',
    '/bootstrap/dist/js/demo.js' =>'bootstrap',
    '/bootstrap/dist/js/adminlte.min.js' =>'bootstrap',
    '/bootstrap/plugins/fontawesome-free/webfonts/fa-regular-400.ttf' =>'bootstrap',
    '/bootstrap/plugins/fontawesome-free/webfonts/fa-regular-400.woff2' =>'bootstrap',
    '/bootstrap/plugins/fontawesome-free/webfonts/fa-solid-900.woff' =>'bootstrap',
    '/bootstrap/plugins/fontawesome-free/webfonts/fa-regular-400.woff' =>'bootstrap',
    '/bootstrap/plugins/fontawesome-free/webfonts/fa-solid-900.ttf' =>'bootstrap',
];